import Fuse from "fuse.js";

// Master Q&A pairs (replace with your full 100+ questions array)
export const responses: { question: string; answer: string }[] = [
  { question: "hello", answer: "Hi there 👋, how can I help you?" },
  { question: "hi", answer: "Hey! How are you doing today?" },
  { question: "pricing", answer: "Our pricing details are available on the pricing page." },
  { question: "support", answer: "You can reach support via email or live chat 24/7." },
  { question: "bye", answer: "Goodbye! Have a great day 🌟" },
  { question: "What is the name of this church?", answer: "This is [Church Name], a Christ-centered family of believers committed to worship, discipleship, and service." },
  { question: "Where is the church located?", answer: "We are located at [full address]. You can also find us on Google Maps here: [map link]." },
  { question: "What are your service times?", answer: "Our regular services are held on Sundays at [time] and Wednesdays at [time]. Special events may have different times." },
  { question: "Who is the pastor?", answer: "Our lead pastor is [Pastor’s Name], supported by a dedicated pastoral and leadership team." },
  { question: "What denomination is this church?", answer: "We are a [denomination name] church, rooted in biblical teaching and open to all who desire to know Christ." },
  { question: "How long has this church been around?", answer: "Our church was founded in [year], and by God’s grace has continued to grow ever since." },
  { question: "What do you believe in?", answer: "We believe in the Bible as God’s Word, salvation through Jesus Christ, the power of the Holy Spirit, and living out God’s love daily." },
  { question: "Do you have a vision or mission statement?", answer: "Yes! Our mission is [insert church mission]. Our vision is [insert vision]." },
  { question: "What languages are services held in?", answer: "Our main services are in [language], and we provide interpretation in [other languages if available]." },
  { question: "Do you stream services online?", answer: "Yes! You can watch our live stream on YouTube, Facebook, or directly from our website under “Live Service.”" },
  { question: "How long does a service last?", answer: "A typical Sunday service lasts about [time, e.g., 2 hours], including worship, teaching, and prayer." },
  { question: "What should I wear to church?", answer: "Come as you are! Some dress formally, others casually. What matters most is your heart for God." },
  { question: "Do you have Sunday School?", answer: "Yes, we offer Sunday School for children and teens during service times." },
  { question: "Is there a choir or worship team?", answer: "Yes, our vibrant worship team leads us in praise and worship every service." },
  { question: "Can visitors take Holy Communion?", answer: "Yes, all believers in Christ are welcome to partake in Holy Communion." },
  { question: "Do you baptize people?", answer: "Yes, we conduct water baptisms. If you’re interested, you can register through our baptism form here: [link]." },
  { question: "Do you dedicate babies?", answer: "Yes, baby dedications are available. Kindly contact the church office to schedule." },
  { question: "Do you have midweek services?", answer: "Yes, we meet on [day and time] for Bible study and prayer." },
  { question: "Are your services free to attend?", answer: "Yes! All our services are open and free for everyone." },
  { question: "Do you hold night vigils?", answer: "Yes, we host monthly night vigils on [day/time]. You are welcome to join." },
  { question: "Do you have a youth ministry?", answer: "Yes, our youth ministry meets on [day/time] to encourage and guide young people in faith." },
  { question: "Is there a children’s church?", answer: "Yes! We provide fun, safe, and faith-filled classes for children during services." },
  { question: "Do you have a women’s fellowship?", answer: "Yes, our women’s fellowship meets on [day/time] to build women of faith and purpose." },
  { question: "What about men’s fellowship?", answer: "Yes, men’s fellowship meets on [day/time], focusing on leadership, faith, and brotherhood." },
  { question: "Do you have small groups?", answer: "Yes, we meet in home fellowships across different locations. You can join one near you." },
  { question: "Is there a choir I can join?", answer: "Yes! We welcome committed singers and instrumentalists. Reach out for auditions." },
  { question: "Do you have a marriage counseling ministry?", answer: "Yes, we provide premarital and marital counseling. You can book an appointment here: [link]." },
  { question: "Do you support the poor or needy?", answer: "Yes, through our welfare ministry, we provide support to families and individuals in need." },
  { question: "Do you have a student ministry?", answer: "Yes, we support students with fellowship, mentorship, and outreach programs." },
  { question: "Is there a prayer team?", answer: "Yes, our prayer team intercedes daily and is available to pray with you." },
  { question: "What special events are coming up?", answer: "You can find upcoming events on our events page here: [link]." },
  { question: "Do you host annual conventions?", answer: "Yes, we host annual conventions every [month]." },
  { question: "Do you hold revival services?", answer: "Yes, we have periodic revival and crusade services. Stay updated on our events page." },
  { question: "Do you have Christmas and Easter services?", answer: "Yes, we celebrate both with special services and activities." },
  { question: "Do you host weddings?", answer: "Yes, our church is available for weddings. Kindly speak with our admin office for booking." },
  { question: "Can I book the church hall for an event?", answer: "Yes, our facilities are available for bookings. Please contact us for details." },
  { question: "Do you host retreats or camps?", answer: "Yes, we organize retreats and camps for spiritual growth." },
  { question: "Do you have evangelism programs?", answer: "Yes, we regularly go out to share the gospel in our community." },
  { question: "Do you do charity outreaches?", answer: "Yes, our welfare team organizes outreaches to hospitals, orphanages, and communities." },
  { question: "Can non-members attend your events?", answer: "Absolutely! All our programs are open to everyone." },
  { question: "How can I become a member?", answer: "You can join our membership class by registering here: [link]." },
  { question: "Do I have to be baptized before becoming a member?", answer: "Baptism is encouraged, but membership starts with your commitment to Christ and to this church family." },
  { question: "Is there a membership fee?", answer: "No, there is no fee. Commitment and participation are what count." },
  { question: "Can I be a member online?", answer: "Yes, we have provisions for online members. You can register here: [link]." },
  { question: "Do members get ID cards?", answer: "Yes, registered members may receive ID cards for easier connection." },
  { question: "Can I transfer membership from another church?", answer: "Yes, you can. Kindly speak with our membership team for details." },
  { question: "How long is the membership process?", answer: "Membership classes usually last [timeframe, e.g., 6 weeks]." },
  { question: "Do I need to attend classes to be a member?", answer: "Yes, membership classes help you understand our values and beliefs." },
  { question: "Can children be members?", answer: "Children are recognized as part of our church family, but official membership begins at a certain age [state age]." },
  { question: "Can I leave membership anytime?", answer: "Yes, though we’d love to support you wherever God leads you." },
  { question: "How can I give online?", answer: "You can give securely through our online giving portal here: [link]." },
  { question: "Do you accept tithes and offerings online?", answer: "Yes, we accept tithes, offerings, and special donations online." },
  { question: "Can I give through bank transfer?", answer: "Yes, our account details are: [bank details]." },
  { question: "Do you accept international donations?", answer: "Yes, you can give from anywhere in the world through our online giving platform." },
  { question: "Is giving compulsory?", answer: "No, giving is voluntary and should come from a cheerful heart." },
  { question: "Do you provide receipts for donations?", answer: "Yes, receipts are issued for all donations." },
  { question: "Can I sponsor a project?", answer: "Yes, we welcome sponsors for our building, missions, and welfare projects." },
  { question: "Do you have a building project?", answer: "Yes, we are currently building [project details]." },
  { question: "Can I set up recurring giving?", answer: "Yes, our platform allows you to set up recurring donations." },
  { question: "Do you accept physical donations (clothes, food, etc.)?", answer: "Yes, kindly bring them to the church office." },
  { question: "Can someone pray for me?", answer: "Yes, please share your request and our prayer team will intercede for you." },
  { question: "Do you offer counseling?", answer: "Yes, we provide spiritual and family counseling. You can book a session here: [link]." },
  { question: "Can I meet the pastor for prayer?", answer: "Yes, appointments with the pastor can be scheduled through our office." },
  { question: "Do you have a prayer hotline?", answer: "Yes, you can call [number] anytime for prayer." },
  { question: "Can I send a private prayer request?", answer: "Yes, use our confidential prayer request form here: [link]." },
  { question: "Do you have fasting and prayer programs?", answer: "Yes, we fast and pray collectively on [days/months]." },
  { question: "Do you pray for the sick?", answer: "Yes, we pray for healing and trust God to restore health." },
  { question: "Can I request deliverance prayers?", answer: "Yes, our deliverance team is available for those in need." },
  { question: "Do you pray for students and exams?", answer: "Yes, we pray for success in studies and career." },
  { question: "Do you pray for businesses?", answer: "Yes, we bless and pray for businesses to prosper." },
  { question: "Do you offer Bible study?", answer: "Yes, Bible study holds every [day/time]." },
  { question: "Do you have online Bible classes?", answer: "Yes, you can join through Zoom or our website link." },
  { question: "Can I download sermons?", answer: "Yes, past sermons are available for download here: [link]." },
  { question: "Do you have daily devotionals?", answer: "Yes, we publish daily devotionals on our website and social media." },
  { question: "Can I ask Bible questions here?", answer: "Yes! Please type your Bible question, and we’ll do our best to answer." },
  { question: "Do you teach new converts?", answer: "Yes, we have discipleship classes for new believers." },
  { question: "Do you have a Bible school?", answer: "Yes, we run a Bible school for deeper training in God’s Word." },
  { question: "Do you provide study materials?", answer: "Yes, you can access study notes, books, and sermons online." },
  { question: "Can I buy Christian books from your church?", answer: "Yes, we have a bookstore onsite and online." },
  { question: "Do you share sermon outlines?", answer: "Yes, outlines are available in the media section of our website." },
  { question: "Is this church open to first-time visitors?", answer: "Yes! We love welcoming new faces every week." },
  { question: "Will I be recognized as a first-timer?", answer: "Yes, we acknowledge and welcome first-timers warmly." },
  { question: "Do you have a welcome team?", answer: "Yes, our welcome team is ready to receive and guide you." },
  { question: "Can I bring a friend who isn’t Christian?", answer: "Yes, everyone is welcome to experience God’s love." },
  { question: "Is there parking available?", answer: "Yes, we provide secure parking for members and visitors." },
  { question: "Do you have transport services?", answer: "Yes, we provide buses/shuttles for those who need a ride." },
  { question: "Will I pay for anything as a visitor?", answer: "No, all services are free. Giving is voluntary." },
  { question: "Can I meet the pastor after service?", answer: "Yes, first-timers are encouraged to meet our pastor." },
  { question: "Do you give gifts to first-timers?", answer: "Yes, we have a special gift bag to appreciate your presence." },
  { question: "Can I bring my children?", answer: "Yes, children are welcome and cared for in children’s church." },
  { question: "How can I join online service?", answer: "You can join via YouTube, Facebook, or our website livestream link." },
  { question: "Do you have a mobile app?", answer: "Yes, download our app on [App Store/Google Play] for sermons, giving, and updates." },
  { question: "How do I subscribe to newsletters?", answer: "Sign up for our newsletter here: [link]." },
  { question: "Can I get event reminders?", answer: "Yes, join our WhatsApp/Telegram group for reminders." },
  { question: "How do I follow your social media?", answer: "Follow us on [Facebook/Instagram/Twitter/YouTube links]." },
  { question: "Can I download church photos/videos?", answer: "Yes, visit our media gallery here: [link]." },
  { question: "Do you have podcasts?", answer: "Yes, our sermons are available as podcasts on Spotify and Apple Podcasts." },
  { question: "How can I contact the church office?", answer: "Call us on [phone number] or email us at [email]." },
  { question: "How do I volunteer online?", answer: "Fill out our volunteer form here: [link]." },
  { question: "What should I do if I have more questions?", answer: "Please leave your name and contact details, and a church representative will reach out to you." }
];

// Synonym dictionary mapping user variations → canonical questions
export const synonyms: Record<string, string> = {
  // greetings
  hey: "hi",
  greetings: "hello",
  howdy: "hello",

  // pricing
  cost: "pricing",
  rate: "pricing",
  charges: "pricing",
  fees: "pricing",

  // support
  help: "support",
  assistance: "support",
  service: "support",
  aid: "support",

  // farewell
  goodbye: "bye",
  cya: "bye",
  farewell: "bye",

  // 🔽 Add synonyms for your extended Q&A list
  // 🔽 Add synonyms here

// General church info
church: "what is the name of this church?",
assembly: "what is the name of this church?",
location: "where is the church located?",
address: "where is the church located?",
place: "where is the church located?",
times: "what are your service times?",
schedule: "what are your service times?",
pastor: "who is the pastor?",
reverend: "who is the pastor?",
minister: "who is the pastor?",
denomination: "what denomination is this church?",
background: "what denomination is this church?",
founded: "how long has this church been around?",
history: "how long has this church been around?",
beliefs: "what do you believe in?",
doctrine: "what do you believe in?",
faith: "what do you believe in?",
mission: "do you have a vision or mission statement?",
vision: "do you have a vision or mission statement?",
languages: "what languages are services held in?",
translation: "what languages are services held in?",
stream: "do you stream services online?",
online: "do you stream services online?",
livestream: "do you stream services online?",
duration: "how long does a service last?",
length: "how long does a service last?",
dress: "what should i wear to church?",
attire: "what should i wear to church?",

// Ministries & activities
"sunday school": "do you have sunday school?",
"children class": "do you have sunday school?",
choir: "is there a choir or worship team?",
"worship team": "is there a choir or worship team?",
music: "is there a choir or worship team?",
communion: "can visitors take holy communion?",
"lord’s supper": "can visitors take holy communion?",
baptism: "do you baptize people?",
"water baptism": "do you baptize people?",
dedication: "do you dedicate babies?",
"baby dedication": "do you dedicate babies?",
midweek: "do you have midweek services?",
"bible study": "do you have midweek services?",
free: "are your services free to attend?",
vigils: "do you hold night vigils?",
"all night": "do you hold night vigils?",
youth: "do you have a youth ministry?",
teenagers: "do you have a youth ministry?",
children: "is there a children’s church?",
kids: "is there a children’s church?",
women: "do you have a women’s fellowship?",
ladies: "do you have a women’s fellowship?",
men: "what about men’s fellowship?",
brothers: "what about men’s fellowship?",
"small groups": "do you have small groups?",
"house fellowship": "do you have small groups?",
marriage: "do you have a marriage counseling ministry?",
counseling: "do you have a marriage counseling ministry?",
poor: "do you support the poor or needy?",
needy: "do you support the poor or needy?",
student: "do you have a student ministry?",
campus: "do you have a student ministry?",
"prayer team": "is there a prayer team?",
intercessors: "is there a prayer team?",

// Events
events: "what special events are coming up?",
programs: "what special events are coming up?",
convention: "do you host annual conventions?",
revival: "do you hold revival services?",
crusade: "do you hold revival services?",
christmas: "do you have christmas and easter services?",
easter: "do you have christmas and easter services?",
wedding: "do you host weddings?",
"marriage ceremony": "do you host weddings?",
hall: "can i book the church hall for an event?",
venue: "can i book the church hall for an event?",
retreat: "do you host retreats or camps?",
camp: "do you host retreats or camps?",
evangelism: "do you have evangelism programs?",
outreach: "do you do charity outreaches?",
charity: "do you do charity outreaches?",

// Membership
membership: "how can i become a member?",
join: "how can i become a member?",
register: "how can i become a member?",
transfer: "can i transfer membership from another church?",
classes: "do i need to attend classes to be a member?",
fee: "is there a membership fee?",
id: "do members get id cards?",
quit: "can i leave membership anytime?",

// Giving
giving: "how can i give online?",
donation: "do you accept tithes and offerings online?",
offering: "do you accept tithes and offerings online?",
tithe: "do you accept tithes and offerings online?",
bank: "can i give through bank transfer?",
transfers: "can i give through bank transfer?",
international: "do you accept international donations?",
abroad: "do you accept international donations?",
receipt: "do you provide receipts for donations?",
sponsor: "can i sponsor a project?",
project: "do you have a building project?",
recurring: "can i set up recurring giving?",
"physical donations": "do you accept physical donations (clothes, food, etc.)?",
clothes: "do you accept physical donations (clothes, food, etc.)?",
food: "do you accept physical donations (clothes, food, etc.)?",

// Prayer & Counseling
prayer: "can someone pray for me?",
counsel: "do you offer counseling?",
"pastor prayer": "can i meet the pastor for prayer?",
hotline: "do you have a prayer hotline?",
"private prayer": "can i send a private prayer request?",
fasting: "do you have fasting and prayer programs?",
healing: "do you pray for the sick?",
deliverance: "can i request deliverance prayers?",
"students prayer": "do you pray for students and exams?",
exam: "do you pray for students and exams?",
business: "do you pray for businesses?",

// Bible & Teaching
study: "do you offer bible study?",
class: "do you have online bible classes?",
sermons: "can i download sermons?",
devotionals: "do you have daily devotionals?",
"daily bread": "do you have daily devotionals?",
"bible school": "do you have a bible school?",
discipleship: "do you teach new converts?",
materials: "do you provide study materials?",
books: "can i buy christian books from your church?",
outlines: "do you share sermon outlines?",

// Visitors & First timers
visitor: "is this church open to first-time visitors?",
"first time": "will i be recognized as a first-timer?",
welcome: "do you have a welcome team?",
friend: "can i bring a friend who isn’t christian?",
parking: "is there parking available?",
transport: "do you have transport services?",
shuttle: "do you have transport services?",
ride: "do you have transport services?",
gifts: "do you give gifts to first-timers?",
"children welcome": "can i bring my children?",

// Media & Tech
"online service": "how can i join online service?",
app: "do you have a mobile app?",
newsletter: "how do i subscribe to newsletters?",
reminders: "can i get event reminders?",
"social media": "how do i follow your social media?",
photos: "can i download church photos/videos?",
videos: "can i download church photos/videos?",
podcast: "do you have podcasts?",

// Contact & Volunteering
contact: "how can i contact the church office?",
phone: "how can i contact the church office?",
email: "how can i contact the church office?",
volunteer: "how do i volunteer online?",
questions: "what should i do if i have more questions?",
helping: "what should i do if i have more questions?",
};

const fuse = new Fuse(responses, { keys: ["question"], threshold: 0.4 });

export function getFuzzyResponse(input: string): string | null {
  let normalized = input.toLowerCase().trim();

  // If multiple words, check each and replace with canonical synonym if found
  const words = normalized.split(/\s+/).map((word) => synonyms[word] || word);
  normalized = words.join(" ");

  // Run fuzzy search on normalized text
  const result = fuse.search(normalized);

  return result.length ? result[0].item.answer : null;
}
